// <auto-generated />
using LccWebAPI.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LccWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180406214314_addedNewFieldsAndRenames")]
    partial class addedNewFieldsAndRenames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("GameDate");

                    b.Property<TimeSpan>("GameDuration");

                    b.Property<long>("GameId");

                    b.Property<string>("GamePatch");

                    b.Property<int?>("WinningTeamId");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Assists");

                    b.Property<int>("ChampionId");

                    b.Property<long>("ChampionLevel");

                    b.Property<long>("DamageDealtToObjectives");

                    b.Property<long>("DamageDealtToTurrets");

                    b.Property<long>("Deaths");

                    b.Property<long>("DoubleKills");

                    b.Property<bool>("FirstBloodAssist");

                    b.Property<bool>("FirstBloodKill");

                    b.Property<bool>("FirstInhibitorAssist");

                    b.Property<bool>("FirstInhibitorKill");

                    b.Property<bool>("FirstTowerAssist");

                    b.Property<bool>("FirstTowerKill");

                    b.Property<long>("GoldEarned");

                    b.Property<long>("GoldSpent");

                    b.Property<long>("InhibitorKills");

                    b.Property<long>("KillingSprees");

                    b.Property<long>("Kills");

                    b.Property<long>("LargestCriticalStrike");

                    b.Property<long>("LargestKillingSpree");

                    b.Property<long>("LargestMultiKill");

                    b.Property<long>("MagicDamageDealt");

                    b.Property<long>("MagicDamageDealtToChampions");

                    b.Property<long>("MagicDamageTaken");

                    b.Property<long>("MatchTeamId");

                    b.Property<int?>("MatchTeamId1");

                    b.Property<long>("NeutralMinionsKilled");

                    b.Property<long>("NeutralMinionsKilledEnemyJungle");

                    b.Property<long>("NeutralMinionsKilledTeamJungle");

                    b.Property<long>("ObjectivePlayerScore");

                    b.Property<int>("ParticipantId");

                    b.Property<long>("PentaKills");

                    b.Property<long>("PhysicalDamageDealt");

                    b.Property<long>("PhysicalDamageDealtToChampions");

                    b.Property<long>("PhysicalDamageTaken");

                    b.Property<long>("PlayerId");

                    b.Property<long>("QuadraKills");

                    b.Property<long>("SightWardsBoughtInGame");

                    b.Property<int>("TeamId");

                    b.Property<long>("TimeCCingOthers");

                    b.Property<long>("TotalDamageDealt");

                    b.Property<long>("TotalDamageDealtToChampions");

                    b.Property<long>("TotalDamageTaken");

                    b.Property<long>("TotalHeal");

                    b.Property<long>("TotalMinionsKilled");

                    b.Property<long>("TotalScoreRank");

                    b.Property<long>("TotalTimeCrowdControlDealt");

                    b.Property<long>("TotalUnitsHealed");

                    b.Property<long>("TrinketId");

                    b.Property<long>("TrueDamageDealt");

                    b.Property<long>("TrueDamageDealtToChampions");

                    b.Property<long>("TrueDamageTaken");

                    b.Property<long>("TurretKills");

                    b.Property<long>("VisionScore");

                    b.Property<long>("VisionWardsBoughtInGame");

                    b.Property<long>("WardsPlaced");

                    b.HasKey("Id");

                    b.HasIndex("MatchTeamId1");

                    b.ToTable("MatchPlayer");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.MatchTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaronKills");

                    b.Property<int>("DragonKills");

                    b.Property<int>("InhibitorKills");

                    b.Property<int>("MatchId");

                    b.Property<int>("RiftHeraldKills");

                    b.Property<int>("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchTeam");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ItemId");

                    b.Property<int>("ItemSlot");

                    b.Property<int>("MatchPlayerId");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("PlayerItem");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.PlayerRune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MatchPlayerId");

                    b.Property<long?>("RuneId");

                    b.Property<int>("RuneSlot");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("PlayerRune");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.PlayerSummonerSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MatchPlayerId");

                    b.Property<long?>("SummonerSpellId");

                    b.Property<int>("SummonerSpellSlot");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId");

                    b.ToTable("PlayerSummonerSpell");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbStaticData.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChampionId");

                    b.Property<string>("ChampionName");

                    b.Property<string>("ImageFull");

                    b.HasKey("Id");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbStaticData.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageFull");

                    b.Property<int>("ItemId");

                    b.Property<string>("ItemName");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbStaticData.Rune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageFull");

                    b.Property<int>("RuneId");

                    b.Property<string>("RuneName");

                    b.HasKey("Id");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbStaticData.SummonerSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageFull");

                    b.Property<int>("SummonerSpellId");

                    b.Property<string>("SummonerSpellName");

                    b.HasKey("Id");

                    b.ToTable("SummonerSpells");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbSummoner.Summoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccountId");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<long>("Level");

                    b.Property<int>("ProfileIconId");

                    b.Property<DateTime>("RevisionDate");

                    b.Property<long>("SummonerId");

                    b.Property<string>("SummonerName");

                    b.HasKey("Id");

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.MatchPlayer", b =>
                {
                    b.HasOne("LccWebAPI.Models.DbMatch.MatchTeam", "MatchTeam")
                        .WithMany("Players")
                        .HasForeignKey("MatchTeamId1");
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.MatchTeam", b =>
                {
                    b.HasOne("LccWebAPI.Models.DbMatch.Match", "Match")
                        .WithMany("Teams")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.PlayerItem", b =>
                {
                    b.HasOne("LccWebAPI.Models.DbMatch.MatchPlayer", "MatchPlayer")
                        .WithMany("Items")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.PlayerRune", b =>
                {
                    b.HasOne("LccWebAPI.Models.DbMatch.MatchPlayer", "MatchPlayer")
                        .WithMany("Runes")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LccWebAPI.Models.DbMatch.PlayerSummonerSpell", b =>
                {
                    b.HasOne("LccWebAPI.Models.DbMatch.MatchPlayer", "MatchPlayer")
                        .WithMany("SummonerSpells")
                        .HasForeignKey("MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
