// <auto-generated />
using LccWebAPI.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RiotSharp.MatchEndpoint.Enums;
using RiotSharp.Misc;
using System;

namespace LccWebAPI.Migrations.MatchReference
{
    [DbContext(typeof(MatchReferenceContext))]
    partial class MatchReferenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LccWebAPI.Models.LccMatchReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ChampionId");

                    b.Property<long>("GameId");

                    b.Property<int>("Lane");

                    b.Property<int>("PlatformId");

                    b.Property<string>("Queue");

                    b.Property<int>("Region");

                    b.Property<int>("Role");

                    b.Property<int>("Season");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("MatchReferences");
                });
#pragma warning restore 612, 618
        }
    }
}
